### PR TITLE
Fix kafka build

### PR DESCRIPTION
**Pull request by dougszumski**
Kafka version 1.0.1 is not in repositories
anymore, need to update to 1.0.2

Change-Id: I27ee1240a79223f2d2fcc7d311c8ac83126ca092

### CODE REVIEW

**Comment by jovial** [comment]
If you want to avoid this happening again, you could use the apache archive: http://archive.apache.org/dist/kafka/1.0.2/kafka_2.12-1.0.2.tgz

**Comment by dougszumski** [comment]
Cheers, I see that has the old file. I will make a todo to fix it upstream and backport.

**Comment by jovial** [comment]
For example, here is old release: http://archive.apache.org/dist/kafka/1.0.1/kafka_2.12-1.0.1.tgz

**Comment by dougszumski** [comment]
5GB per IP on the archive, I suppose it might be possible to run into the limit in upstream CI, particularity as there are other apache wares.

**Comment by jovial** [comment]
> 5GB per IP on the archive, I suppose it might be possible to run into the limit in upstream CI, particularity as there are other apache wares.

Didn't notice that - guess that rules that out then

**Comment by dougszumski** [comment]
I wonder if CI caches it, might be ok in that case, I'll ask on IRC

**Pull request merged**
