### PR TITLE
Update Prometheus services to latest releases

### PR DESCRIPTION
**Pull request by priteau**
blackbox_exporter 0.22.0 -> 0.24.0
elasticsearch_exporter 1.5.0 -> 1.6.0
haproxy_exporter 0.13.0 -> 0.15.0
memcached_exporter 0.10.0 -> 0.13.0
mysqld_exporter 0.14.0 -> 0.15.0
node_exporter 1.4.0 -> 1.7.0
ovn_exporter 1.0.6 -> 1.0.7
prometheus 2.38.0 -> 2.48.0
prometheus_alertmanager 0.24.0 -> 0.26.0
prometheus_cadvisor 0.45.0 -> 0.47.2
prometheus_mtail v3.0.0-rc50 -> v3.0.0-rc52
prometheus_msteams 1.5.1 -> 1.5.2

Change-Id: If3f6ff059bedba5c92d97442d77e44aeecef71c4 (cherry picked from commit 773c6963e2405af3d535c41d7794361a079b71c4)

### CODE REVIEW

**Comment by markgoddard** [comment]
We override node exporter version in SKC: https://github.com/stackhpc/stackhpc-kayobe-config/blob/stackhpc/2023.1/etc/kayobe/kolla.yml#L354

**Comment by markgoddard** [comment]
Have the new versions been tested?

**Comment by priteau** [comment]
I have tested Alertmanager. It works fine so far and some of the metrics that it exports, such as `alertmanager_alerts`, were fixed.

**Comment by priteau** [comment]
Closing since we will soon upgrade to Caracal.

**Pull request closed without merging**
